---
run:
  timeout: 10m
  tests: true
linters:
  enable-all: false
  enable:
    - bodyclose
    - errcheck
    - gofmt
    - goimports
    - govet
    - gosimple
    - ineffassign
    - misspell
    - nilerr
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
  disable:
    - deadcode
