

run:
  timeout: 10m
  skip-dirs:
    - vendor$
  tests: true
  skip-dirs-use-default: false
linters:
  enable-all: false
  enable:
    - errcheck
    - gosimple
    - govet
    - gofmt
    - goimports
    - ineffassign
    - typecheck
    - stylecheck
    - unused
    - misspell
    - whitespace
  disable:
    - deadcode
