run:
  timeout: 10m
  skip-dirs:
    - vendor$
  tests: true
  skip-dirs-use-default: false
linters:
  enable-all: false
  enable:
    - bodyclose
    - errcheck
    - gofmt
    - goimports
    - govet
    - gosimple
    - ineffassign
    - misspell
    - nilerr
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
  disable:
    - deadcode
