# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
---
project_name: loli
env:
  - GO111MODULE=on
release:
  github:
    owner: lpmatos
    name: loli
  name_template: "{{.ProjectName}}-v{{.Version}}"
builds:
  - id: loli
    binary: loli
    env:
      - CGO_ENABLED=0
    main: ./cmd/loli/main.go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm64
    mod_timestamp: "{{.CommitTimestamp}}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X "github.com/lpmatos/loli/internal/version.cliVersion={{.Env.CLIENT_VERSION}}" -X "github.com/lpmatos/loli/internal/version.builtDate={{.CommitDate}}" -X "github.com/lpmatos/loli/internal/version.builtBy=goreleaser" -X "github.com/lpmatos/loli/internal/version.commit={{.Commit}}" -X "github.com/lpmatos/loli/internal/version.commitShort={{.ShortCommit}}" -X "github.com/lpmatos/loli/internal/version.commitBranch={{.Env.GIT_BRANCH}}" -X "github.com/lpmatos/loli/internal/version.goVersion={{.Env.GO_VERSION}}"
archives:
  - name_template: "{{.ProjectName}}_v{{.Version}}_{{.Os}}-{{.Arch}}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      "386": i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
snapshot:
  name_template: "SNAPSHOT-{{ .Commit }}"
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256
changelog:
  skip: true
dist: dist
before:
  hooks:
    - make clean
    - go generate ./...
    - go mod download
    - chmod a+x ./scripts/variables.sh
    - ./scripts/variables.sh
github_urls:
  download: https://github.com
