# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
---
project_name: loli
env:
  - GO111MODULE=on
release:
  github:
    owner: lpmatos
    name: loli
  name_template: "{{.ProjectName}}-v{{.Version}}"
builds:
  - id: loli
    binary: loli
    env:
      - CGO_ENABLED=0
    main: ./cmd/loli/main.go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
    mod_timestamp: "{{.CommitTimestamp}}"
    flags:
      - -trimpath
    ldflags:
     - -s -w -X "github.com/lpmatos/loli/pkg/cmd/version.builtDate={{.CommitDate}}" -X "github.com/lpmatos/loli/pkg/cmd/version.builtBy=goreleaser" -X "github.com/lpmatos/loli/pkg/cmd/version.commit={{.Commit}}" -X "github.com/lpmatos/loli/pkg/cmd/version.commitShort={{.ShortCommit}}"
archives:
  - id: "loli"
    name_template: "{{.ProjectName}}_v{{.Version}}_{{.Os}}-{{.Arch}}"
    builds: [ "loli" ]
    format: binary
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      "386": i386
      amd64: x86_64
    files:
      - LICENSE
      - README.md
snapshot:
  name_template: "SNAPSHOT-{{ .Commit }}"
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256
changelog:
  skip: true
dist: dist
before:
  hooks:
    - go mod download
    - go generate ./...
github_urls:
  download: https://github.com
