repos:
-   repo: https://github.com/zricethezav/gitleaks
    rev: v7.6.1
    hooks:
    -   id: gitleaks
-   repo: https://github.com/commitizen-tools/commitizen
    rev: v2.19.0
    hooks:
    -   id: commitizen
        stages: [commit-msg]
exclude: (^vendor/|_test.go$)
