name: CI

on:
  push:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04

    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: Secret Dection
        uses: zricethezav/gitleaks-action@master
        with:
          config-path: .gitleaks.toml
        continue-on-error: false

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tool_name: golangci-lint

      - name: Hadolint
        uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: Dockerfile
          config: .hadolint.yml

  bump:
    name: GitHub Bump
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Git list tags
        run: |
          git tag --list

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install

      - name: Bump version
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Git list tags
        run: |
          git tag --list
