name: CI

on:
  push:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04

    steps:
    - name: Check out code from GitHub
      uses: actions/checkout@v3.0.2
      with:
        fetch-depth: 0

    - name: Secret Detection
      uses: zricethezav/gitleaks-action@fd822c19c822326224ff07fadec08a3446f051f3
      with:
        config-path: ${{ github.workspace }}/.github/config/.gitleaks.toml
      continue-on-error: false

    - name: Hadolint
      uses: hadolint/hadolint-action@v2.1.0
      with:
        dockerfile: Dockerfile
        config: ${{ github.workspace }}/.github/config/.hadolint.yml
