name: GoLang Release

on:
  workflow_dispatch:
    inputs:
      git-tag:
        description: Git Tag (Optional)
        default: v1.0.0
        required: true

jobs:
  goreleaser:
    name: "Create Go Release"
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.5

      - name: Get Details
        id: get_details
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CLIENT_VERSION: ${{ steps.get_details.outputs.SOURCE_TAG }}
          GIT_BRANCH: ${{ steps.get_details.outputs.SOURCE_BRANCH }}
          GO_VERSION: 1.16.5
