name: Linter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linter:
    name: golangci-lint
    runs-on: ubuntu-20.04
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: golangci-lint
      uses: reviewdog/action-golangci-lint@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tool_name: golangci-lint
