name: Go Release

on:
  push:
    tags:
    - 'v*'

jobs:
  goreleaser:
    name: "Create Go Release"
    runs-on: ubuntu-20.04

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.6

      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CLIENT_VERSION: ${{ github.ref }}
          GIT_BRANCH: ${{ github.base_ref }}
          GO_VERSION: 1.15.6
