name: Release

on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        default: main
        required: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        if: github.event.inputs.git-ref == 'main'

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
        if: github.event.inputs.git-ref == 'main'

      - name: Install dependencies
        run: npm install
        if: github.event.inputs.git-ref == 'main'

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.event.inputs.git-ref == 'main'

  goreleaser:
    name: "Create Go Release"
    needs: release
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - run: |
          git fetch --unshallow --tags
          echo $?
          git tag --list

      - name: Read .go-version
        run: echo ::set-output name=GOVERSION::$(cat .go-version)
        id: goversion

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.goversion.outputs.GOVERSION }}

      - name: Get Details
        id: get_details
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CLIENT_VERSION: ${{ steps.get_details.outputs.SOURCE_TAG }}
          GIT_BRANCH: ${{ steps.get_details.outputs.SOURCE_BRANCH }}
          GO_VERSION: ${{ steps.goversion.outputs.GOVERSION }}
