name: Release

on:
  push:
    tags:
      - '*'

jobs:
  go-release:
    name: Go Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Git list tags
        run: |
          git tag --list

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.5

      - name: Get Details
        id: get_details
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          CLIENT_VERSION: ${{ steps.get_details.outputs.SOURCE_TAG }}
          GIT_BRANCH: ${{ steps.get_details.outputs.SOURCE_BRANCH }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GO_VERSION: 1.16.5
