name: "Secrets Detection"

on: [push,pull_request]

jobs:
  gitleaks:
    name: GitLeaks
    runs-on: ubuntu-20.04

    steps:
    - name: Check out code from GitHub
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0

    - name: gitleaks
      uses: zricethezav/gitleaks-action@master
      with:
        config-path: .gitleaks.toml
