name: Semantic Release

on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref
        default: main
        required: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
      if: github.event.inputs.git-ref == 'main'

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'
      if: github.event.inputs.git-ref == 'main'

    - name: Install dependencies
      run: npm install
      if: github.event.inputs.git-ref == 'main'

    - name: Release
      run: npx semantic-release
      env:
        CI: true
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      if: github.event.inputs.git-ref == 'main'
